import { InvoicesService } from './invoices.module';

/**
 * Phase 5 (C-08) — Seller->Customer product tax invoice and Remont->Seller platform fee
 * document are legally distinct transactions (different issuer, different recipient) but
 * previously shared the SAME invoice.invoiceNumber (both pages just read
 * `invoice.invoiceNumber`). This proves each page generated by generateForOrder() now gets
 * its own number, in its own series, and that the split only happens for a page that
 * actually has content — a pure-SERVICE order with no seller never allocates an unused
 * PARTNER_SETTLEMENT/PLATFORM_FEE number.
 */

function makeService() {
  const prisma: any = {
    order: { findUnique: jest.fn(), update: jest.fn(async (args: any) => ({ id: args.where.id, ...args.data })) },
    invoice: {
      findUnique: jest.fn(async () => null),
      create: jest.fn(async (args: any) => ({ id: 'inv-1', ...args.data })),
    },
    siteSetting: { findMany: jest.fn(async () => []), findUnique: jest.fn(async () => null) },
    taxConfig: { findMany: jest.fn(async () => []) },
  };
  let seq = 0;
  prisma.$queryRaw = jest.fn(async () => [{ lastNumber: ++seq }]);
  prisma.$transaction = jest.fn(async (fn: any) => fn(prisma));
  return { svc: new InvoicesService(prisma), prisma };
}

function baseOrder(overrides: any = {}) {
  return {
    id: 'o1', customerId: 'cust-1', vendor: null,
    invoice: null, orderNumber: 'REM-1', type: 'PRODUCT',
    subtotal: 1000, totalAmount: 1180, gstAmount: 180, serviceAmount: 0,
    remontCommission: 0, platformCharges: 0, snapshotState: 'Madhya Pradesh',
    billingTransactionType: null, couponDiscount: 0, membershipDiscount: 0, discountAllocation: null,
    service: null, serviceItems: [], extraWorkItems: [], items: [],
    ...overrides,
  };
}

describe('InvoicesService.generateForOrder — legal document separation (C-08)', () => {
  it('MARKETPLACE_PRODUCT with a Remont commission — customer, seller-tax-invoice and platform-fee document each get their OWN distinct number/series', async () => {
    const { svc, prisma } = makeService();
    prisma.order.findUnique.mockResolvedValue(baseOrder({
      type: 'PRODUCT', vendor: null, remontCommission: 100,
      items: [{
        quantity: 1, unitPrice: 1000,
        product: { name: 'Widget', hsnSac: null, gstOverridePercent: null, gstInclusive: null, categoryId: 'cat-1', unit: 'piece', vendor: { businessName: 'Seller Co', address: 'Addr', gstNumber: '23AAAAA0000A1Z5', state: 'Madhya Pradesh' } },
      }],
    }));
    await svc.generateForOrder('o1');
    const data = prisma.invoice.create.mock.calls[0][0].data;

    expect(data.invoiceNumber).toMatch(/^INV-CTI-\d{4}-\d{2}-\d{6}$/); // customer tax invoice series
    expect(data.remontDocumentNumber).toMatch(/^INV-PFI-\d{4}-\d{2}-\d{6}$/); // Remont's own platform-fee series
    // The audit's exact concern: these must never be the same number.
    expect(data.invoiceNumber).not.toBe(data.remontDocumentNumber);
    // No partner/service line exists on a marketplace order — never allocate an unused number for it.
    expect(data.vendorDocumentNumber).toBeNull();
  });

  it('PLATFORM_SERVICE (partner fulfils the job, Remont takes a fee) — partner settlement and platform-fee documents each get their own number, distinct from the customer summary', async () => {
    const { svc, prisma } = makeService();
    prisma.order.findUnique.mockResolvedValue(baseOrder({
      type: 'SERVICE', vendor: { userId: 'v1', staffType: 'PARTNER', gstin: null },
      serviceAmount: 1000, remontCommission: 150,
      service: { name: 'AC Repair', hsnSac: null, gstOverridePercent: null },
    }));
    await svc.generateForOrder('o1');
    const data = prisma.invoice.create.mock.calls[0][0].data;

    expect(data.invoiceNumber).toMatch(/^INV-CTI-/); // customer-facing booking summary reference
    expect(data.vendorDocumentNumber).toMatch(/^INV-PSI-/); // partner's own settlement document
    expect(data.remontDocumentNumber).toMatch(/^INV-PFI-/); // Remont's own platform-fee document
    const numbers = [data.invoiceNumber, data.vendorDocumentNumber, data.remontDocumentNumber];
    expect(new Set(numbers).size).toBe(3); // all three genuinely distinct — none shared
  });

  it('DIRECT_PROJECT (Remont\'s own team, no partner, no platform fee) — only the customer document is issued', async () => {
    const { svc, prisma } = makeService();
    prisma.order.findUnique.mockResolvedValue(baseOrder({
      type: 'SERVICE', vendor: { userId: 'v1', staffType: 'IN_HOUSE', gstin: null },
      serviceAmount: 1000,
      serviceItems: [{ quantity: 1, unitPrice: 1000, service: { name: 'AC Repair', hsnSac: null, gstOverridePercent: null, unit: 'per visit' } }],
    }));
    await svc.generateForOrder('o1');
    const data = prisma.invoice.create.mock.calls[0][0].data;
    expect(data.invoiceNumber).toMatch(/^INV-CTI-/);
    expect(data.vendorDocumentNumber).toBeNull();
    expect(data.remontDocumentNumber).toBeNull();
  });

  it('a pre-existing invoice (generated before Phase 5) with no vendor/remont document number falls back to the shared invoiceNumber on those pages — never retroactively renumbered', async () => {
    // This models invoice-pdf.ts's fallback (`invoice.vendorDocumentNumber || invoice.invoiceNumber`)
    // directly, since generateForOrder() always populates both fields going forward — the
    // fallback only ever matters for a historical row.
    const legacyInvoice = { invoiceNumber: 'INV-REM-1-0007', vendorDocumentNumber: null, remontDocumentNumber: null };
    expect(legacyInvoice.vendorDocumentNumber || legacyInvoice.invoiceNumber).toBe('INV-REM-1-0007');
    expect(legacyInvoice.remontDocumentNumber || legacyInvoice.invoiceNumber).toBe('INV-REM-1-0007');
  });
});
