import {
  BadRequestException, ConflictException, GatewayTimeoutException, HttpException, Injectable, Logger, ServiceUnavailableException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import sharp from 'sharp';
import { v2 as cloudinary } from 'cloudinary';
import { MediaSource, UserRole } from '@prisma/client';
import { MediaService, PublicMedia } from '../media/media.service';
import { fetchGeneratedImage, generateWithCloudinary, isCloudinaryUrl } from './cloudinary-images';
import {
  AI_IMAGE_PRESETS, AiImageContext, AiImageEntity, AiImagePreset, MAX_CUSTOM_PROMPT_CHARS,
  buildPrompt, parseAiImageEntity, presetCatalogue, resolveStyles, suggestPrompt,
} from './image-presets';

// ═══════════════════════════════════════════════════════════════════════════
// ADMIN AI IMAGE GENERATION
//
// Generates website-ready images for categories, sub-categories, services, products and
// product catalogue sets, so an admin never has to open Cloudinary.
//
// Provider: the CLOUDINARY Image Generation add-on (text_to_image / image_to_image), using
// the platform's existing Cloudinary credentials. There is deliberately no OpenAI fallback
// here — if the add-on is not enabled, the admin gets a clear configuration message. (The
// SELLER product generator is untouched and still uses OpenAI.)
//
// It adds NO storage of its own: the generated bytes go straight through the existing
// central media pipeline (MediaService.ingestImage → validation → ClamAV → sharp → Cloudinary
// → Media row, source AI_GENERATED), exactly like the seller's AI images. The Cloudinary
// folder comes from the media policy's entity mapping, so nothing new is invented here.
//
// Admin generation is FREE inside the application: no wallet debit, no seller/customer
// charge, no AiFeatureUsage row. This service has no wallet or database dependency at all —
// only Cloudinary's own AI credits (an infrastructure cost) are consumed.
//
// Generated images are stored UNATTACHED. They only become an entity's image when the admin
// presses "Use this image" and saves the record — the existing save path then links the
// Media row (AdminService.linkMedia). Nothing is ever silently overwritten.
// ═══════════════════════════════════════════════════════════════════════════

export interface AiImageRequest {
  entity: unknown;
  name?: unknown;
  category?: unknown;
  subCategory?: unknown;
  brand?: unknown;
  details?: unknown;
  styles?: unknown;
  prompt?: unknown;
  count?: unknown;
  views?: unknown;
  /** Existing Remont image URLs to guide generation (Cloudinary image_to_image). */
  referenceImages?: unknown;
}

export interface AiImageActor { id: string; role: UserRole }

@Injectable()
export class AiImageService {
  private readonly logger = new Logger(AiImageService.name);
  /** Model is configurable so it can be changed without touching this feature.
   *  Defaults to FLUX premium (photorealistic). */
  private readonly model: { family: string; tier: string };
  /** One generation at a time per admin — a double-clicked button can't spend twice. */
  private readonly inFlight = new Set<string>();

  constructor(config: ConfigService, private media: MediaService) {
    this.model = {
      family: config.get('CLOUDINARY_AI_MODEL_FAMILY', 'flux'),
      tier: config.get('CLOUDINARY_AI_MODEL_TIER', 'premium'),
    };
  }

  /** Cloudinary is already configured platform-wide (uploads depend on it); whether the
   *  Image Generation ADD-ON is registered can only be learned from a real call, which then
   *  returns an explicit instruction. */
  isConfigured(): boolean {
    return !!cloudinary.config().cloud_name;
  }

  /** Options for the admin UI — styles, defaults, ratios and per-request limits. */
  presets() {
    return { available: this.isConfigured(), model: this.model, presets: presetCatalogue() };
  }

  /** The pre-filled, editable prompt shown in the modal. Costs nothing. */
  suggest(body: AiImageRequest) {
    const entity = parseAiImageEntity(body.entity);
    const ctx = this.context(body);
    const preset = AI_IMAGE_PRESETS[entity];
    const styles = resolveStyles(preset, body.styles);
    return { entity, styles, prompt: suggestPrompt(entity, ctx, styles), aspect: `${preset.aspect.w}:${preset.aspect.h}`, maxCount: preset.maxCount };
  }

  async generate(body: AiImageRequest, actor: AiImageActor, ip?: string) {
    if (!this.isConfigured()) {
      throw new ServiceUnavailableException('Cloudinary is not configured on this server, so images cannot be generated.');
    }
    const entity = parseAiImageEntity(body.entity);
    const preset = AI_IMAGE_PRESETS[entity];
    const ctx = this.context(body);
    const styles = resolveStyles(preset, body.styles);
    const count = this.resolveCount(body.count, preset);
    const customSubject = this.customPrompt(body.prompt);
    const referenceImages = this.resolveReferences(body.referenceImages);
    if (!ctx.name && !customSubject) throw new BadRequestException('Enter a name, or write your own prompt');

    if (this.inFlight.has(actor.id)) {
      throw new ConflictException('An image is already being generated. Please wait for it to finish.');
    }
    this.inFlight.add(actor.id);
    const started = Date.now();
    try {
      const views = preset.views && count > 1 ? this.resolveViews(body.views, preset, count) : [];
      const prompts = Array.from({ length: count }, (_, i) => buildPrompt(preset, styles, ctx, {
        customSubject, viewKey: views[i], hasReference: !!referenceImages.length,
      }));
      this.logger.log(`Admin AI image: user=${actor.id} entity=${entity} count=${count} styles=${styles.join('+')} refs=${referenceImages.length} model=${this.model.family}/${this.model.tier}`);

      // One API call per distinct prompt; a single-prompt request asks for n images at once.
      const buffers: Buffer[] = [];
      const unique = [...new Set(prompts)];
      for (const prompt of unique) {
        const n = prompts.filter((p) => p === prompt).length;
        buffers.push(...await this.callModel(prompt, preset, n, referenceImages));
      }

      const stored = await this.store(buffers, preset, actor);
      this.logger.log(`Admin AI image: ${stored.length} image(s) stored in ${Math.round((Date.now() - started) / 1000)}s by user=${actor.id}`);
      return {
        entity,
        styles,
        prompt: prompts[0],
        aspect: `${preset.aspect.w}:${preset.aspect.h}`,
        model: this.model,
        referenceImages,
        images: stored.map((m, i) => ({
          mediaId: m.id,
          url: m.variants?.full ?? m.deliveryUrl,
          thumb: m.variants?.card ?? m.deliveryUrl,
          publicId: m.storageKey,
          width: m.width,
          height: m.height,
          view: views[i] || null,
        })),
      };
    } finally {
      this.inFlight.delete(actor.id);
    }
  }

  // ─── Internals ────────────────────────────────────────────────────────────

  private context(body: AiImageRequest): AiImageContext {
    const text = (v: unknown, max = 200) => {
      const s = typeof v === 'string' ? v.trim() : '';
      if (s.length > max) throw new BadRequestException('Input is too long');
      return s || undefined;
    };
    return {
      name: text(body.name) || '',
      category: text(body.category),
      subCategory: text(body.subCategory),
      brand: text(body.brand),
      details: text(body.details, 400),
    };
  }

  private customPrompt(raw: unknown): string | undefined {
    if (raw === undefined || raw === null || raw === '') return undefined;
    const prompt = String(raw).trim();
    if (!prompt) return undefined;
    if (prompt.length > MAX_CUSTOM_PROMPT_CHARS) throw new BadRequestException(`Prompt must be under ${MAX_CUSTOM_PROMPT_CHARS} characters`);
    return prompt;
  }

  private resolveCount(raw: unknown, preset: AiImagePreset): number {
    if (raw === undefined || raw === null || raw === '') return 1;
    const n = Number(raw);
    if (!Number.isInteger(n) || n < 1) throw new BadRequestException('Invalid image count');
    if (n > preset.maxCount) throw new BadRequestException(`At most ${preset.maxCount} images can be generated at once`);
    return n;
  }

  private resolveViews(raw: unknown, preset: AiImagePreset, count: number): string[] {
    const all = preset.views!.map((v) => v.key);
    if (raw === undefined || raw === null || (Array.isArray(raw) && !raw.length)) return all.slice(0, count);
    const list = (Array.isArray(raw) ? raw : [raw]).map((v) => {
      const key = String(v).trim().toUpperCase();
      if (!all.includes(key)) throw new BadRequestException(`Unknown view: ${key}`);
      return key;
    });
    return Array.from({ length: count }, (_, i) => list[i % list.length]);
  }

  /**
   * Calls Cloudinary image generation (image_to_image when reference images are supplied,
   * text_to_image otherwise), downloads the short-lived result and normalises the ratio.
   * Provider errors are already mapped to admin-facing messages in cloudinary-images.ts —
   * including the explicit "add-on not enabled" instruction. No provider fallback.
   */
  private async callModel(prompt: string, preset: AiImagePreset, n: number, referenceImages: string[]): Promise<Buffer[]> {
    try {
      const generated = await generateWithCloudinary({
        prompt, width: preset.width, height: preset.height, count: n,
        model: this.model, referenceImages, logger: this.logger,
      });
      const buffers = await Promise.all(generated.slice(0, n).map((g) => fetchGeneratedImage(g.url)));
      return await Promise.all(buffers.map((b) => this.cropToAspect(b, preset)));
    } catch (e: any) {
      if (e instanceof HttpException) throw e; // already a clear, mapped message
      const message = String(e?.message || e);
      this.logger.error(`Admin AI image generation failed: ${message}`);
      if (e?.name === 'AbortError' || /timeout|aborted/i.test(message)) throw new GatewayTimeoutException('Image generation timed out. Please try again.');
      throw new ServiceUnavailableException('Cloudinary image generation failed. Please try again.');
    }
  }

  /** Centre-crops to the preset ratio so every stored image matches the website's boxes
   *  (a safety net: the provider is already asked for these exact pixel dimensions). */
  private async cropToAspect(buf: Buffer, preset: AiImagePreset): Promise<Buffer> {
    const { width = 0, height = 0 } = await sharp(buf).metadata();
    const target = preset.aspect.w / preset.aspect.h;
    if (!width || !height) return buf;
    const current = width / height;
    if (Math.abs(current - target) < 0.01) return buf;
    const box = current > target
      ? { width: Math.round(height * target), height }
      : { width, height: Math.round(width / target) };
    return sharp(buf).resize({ ...box, fit: 'cover', position: 'centre' }).png().toBuffer();
  }

  /** Reference images must be images Remont already stores (Cloudinary URLs) — an admin
   *  uploads one through the normal media endpoint first, or picks an existing product
   *  image. This also stops the generator being used to fetch arbitrary external URLs. */
  private resolveReferences(raw: unknown): string[] {
    if (raw === undefined || raw === null || (Array.isArray(raw) && !raw.length)) return [];
    const list = (Array.isArray(raw) ? raw : [raw]).map((v) => String(v).trim()).filter(Boolean);
    if (list.length > 4) throw new BadRequestException('At most 4 reference images are allowed');
    for (const url of list) {
      if (!isCloudinaryUrl(url)) throw new BadRequestException('Reference images must be images already stored in Remont media');
    }
    return list;
  }

  /**
   * Straight into the central pipeline. All-or-nothing: if any image fails validation,
   * scanning or upload, the ones already stored are removed so a half-finished set never
   * shows up in the Media Library.
   */
  private async store(images: Buffer[], preset: AiImagePreset, actor: AiImageActor): Promise<PublicMedia[]> {
    const settled = await Promise.allSettled(images.map((buffer, i) => this.media.ingestImage({
      buffer,
      originalName: `ai-${preset.entity.toLowerCase()}-${i + 1}.png`,
      entityType: preset.mediaEntityType,
      source: MediaSource.AI_GENERATED,
      actor,
    })));
    const failed = settled.find((r): r is PromiseRejectedResult => r.status === 'rejected');
    const stored = settled.filter((r): r is PromiseFulfilledResult<PublicMedia> => r.status === 'fulfilled').map((r) => r.value);
    if (failed) {
      await Promise.all(stored.map((m) => this.media.remove(m.id, actor).catch(() => undefined)));
      throw failed.reason;
    }
    return stored;
  }
}
