import { BadRequestException, Logger, ServiceUnavailableException } from '@nestjs/common';
import { cloudinaryCredentials } from '../uploads/image-processing';

// ═══════════════════════════════════════════════════════════════════════════
// CLOUDINARY IMAGE GENERATION ADD-ON
// https://cloudinary.com/documentation/image_generation_addon
//
//   POST https://api.cloudinary.com/v2/generate/<cloud>/text_to_image
//   POST https://api.cloudinary.com/v2/generate/<cloud>/image_to_image   (reference images)
//
// Authenticated with the SAME Cloudinary API key/secret the platform already uses for
// uploads — no new provider account, no new secret, nothing exposed to the browser.
//
// Generated with target_type "temporary": Cloudinary returns a short-lived URL, whose bytes
// we then put through the existing MediaService pipeline (ClamAV → sharp → WebP → our own
// public_id → Media row). That keeps ONE storage path and one stored copy per image, instead
// of letting the add-on write a managed asset that bypasses the pipeline.
// ═══════════════════════════════════════════════════════════════════════════

const API_BASE = 'https://api.cloudinary.com/v2/generate';
const REQUEST_TIMEOUT_MS = 120_000;

/** Cloudinary delivery/API hosts — the only hosts we will fetch generated bytes from, and
 *  the only ones accepted as reference images (no arbitrary URL fetching). */
export function isCloudinaryUrl(url: unknown): boolean {
  if (typeof url !== 'string') return false;
  try {
    const u = new URL(url);
    return u.protocol === 'https:' && /(^|\.)cloudinary\.com$/.test(u.hostname);
  } catch {
    return false;
  }
}

export interface CloudinaryModel { family: string; tier: string }

export interface CloudinaryGenerateOptions {
  prompt: string;
  width: number;
  height: number;
  model: CloudinaryModel;
  /** Reference images (image_to_image). Cloudinary accepts up to 4. */
  referenceImages?: string[];
  logger?: Logger;
}

interface GeneratedImage { url: string; width?: number; height?: number }

/** Raised when the account hasn't registered the add-on — surfaced to the admin verbatim. */
export const ADDON_NOT_ENABLED =
  'The Cloudinary Image Generation add-on is not enabled on this Cloudinary account. '
  + 'Register it at cloudinary.com → Add-ons → Image Generation (a free tier is available), then try again.';

export async function generateWithCloudinary(opts: CloudinaryGenerateOptions): Promise<GeneratedImage[]> {
  const { cloudName, apiKey, apiSecret } = cloudinaryCredentials();
  const refs = (opts.referenceImages || []).filter(Boolean);
  if (refs.length > 4) throw new BadRequestException('At most 4 reference images are allowed');
  for (const r of refs) {
    if (!isCloudinaryUrl(r)) throw new BadRequestException('Reference images must be images already stored in Remont media');
  }

  const endpoint = refs.length ? 'image_to_image' : 'text_to_image';
  // One call generates ONE image — the API has no "number of images" parameter, so callers
  // asking for several issue several calls.
  const body: Record<string, any> = {
    prompt: opts.prompt,
    model: { family: opts.model.family, tier: opts.model.tier },
    image_size: { width: opts.width, height: opts.height },
    // Short-lived output: the permanent copy is the one our media pipeline stores.
    target: { target_type: 'temporary' },
  };
  if (refs.length) body.reference_images = refs.map((url) => ({ source_type: 'url', url }));

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  let res: Response;
  try {
    res = await fetch(`${API_BASE}/${encodeURIComponent(cloudName)}/${endpoint}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Basic ${Buffer.from(`${apiKey}:${apiSecret}`).toString('base64')}`,
      },
      body: JSON.stringify(body),
      signal: controller.signal,
    });
  } finally {
    clearTimeout(timer);
  }

  if (!res.ok) {
    const detail = await res.text().catch(() => res.statusText);
    throw cloudinaryGenerationError(res.status, detail, cloudName, endpoint, opts.logger);
  }

  const data: any = await res.json().catch(() => ({}));

  // Documented success shape:
  //   { data: { assets: [ { width, height, storage: { secure_url, public_id, … } } ] },
  //     limits: {…}, request_id: "…" }
  // The generated URL is at data.assets[].storage.secure_url. Flatter variants are still
  // accepted so a minor response change doesn't break generation.
  const assets: any[] = Array.isArray(data?.data?.assets) ? data.data.assets
    : Array.isArray(data?.assets) ? data.assets
      : Array.isArray(data?.data) ? data.data
        : data?.secure_url || data?.url ? [data] : [];
  const images = assets
    .map((a) => ({
      url: a?.storage?.secure_url || a?.storage?.url || a?.secure_url || a?.url,
      width: a?.width,
      height: a?.height,
    }))
    .filter((a) => typeof a.url === 'string' && a.url);

  if (!images.length) {
    // Asynchronous generation (HTTP 202) returns a task to poll instead of an image; we
    // always request synchronous generation, so this means the request was not what we think.
    const pending = res.status === 202 || data?.data?.status === 'pending' || data?.data?.task_id;
    opts.logger?.error(
      `Cloudinary image generation returned no usable image (HTTP ${res.status}, pending=${!!pending}); `
      + `response keys: ${Object.keys(data || {}).join(',') || 'none'}; data keys: ${Object.keys(data?.data || {}).join(',') || 'none'}`,
    );
    if (pending) throw new ServiceUnavailableException('Cloudinary returned an asynchronous generation task, which is not supported here. Please try again.');
    throw new ServiceUnavailableException('Cloudinary image generation returned no image. Please try again.');
  }
  return images;
}

/**
 * Maps a rejected generation request to an admin-facing error that carries Cloudinary's own
 * code and message, and logs the full structured rejection. Error body shape:
 *   { error: { category, code, message },
 *     limits: { addons_quota: [ { type: "image_generation", limit, remaining } ] }, request_id }
 * Classification reads Cloudinary's error fields, never the raw body: the body of an
 * exhausted-quota 429 contains the key "addons_quota", which a raw-text /add-?on/ match would
 * misreport as "add-on not enabled". There is deliberately NO fallback to another provider.
 */
function cloudinaryGenerationError(status: number, detail: string, cloudName: string, endpoint: string, logger?: Logger) {
  let parsed: any = null;
  try { parsed = JSON.parse(detail); } catch { /* non-JSON body — fall back to the raw text */ }
  const code: string = parsed?.error?.code || '';
  const category: string = parsed?.error?.category || '';
  const message: string = String(parsed?.error?.message || (parsed ? '' : detail) || '').slice(0, 300);
  const quota = Array.isArray(parsed?.limits?.addons_quota)
    ? parsed.limits.addons_quota.find((q: any) => q?.type === 'image_generation') || parsed.limits.addons_quota[0]
    : undefined;
  const quotaText = quota ? `${quota.remaining}/${quota.limit} remaining` : 'n/a';

  logger?.error(
    `Cloudinary image generation rejected: cloud=${cloudName} endpoint=${endpoint} HTTP ${status}`
    + ` code=${code || '-'} category=${category || '-'} quota=${quotaText} request_id=${parsed?.request_id || '-'}`
    + ` message="${message || '-'}" body=${detail.slice(0, 500)}`,
  );

  const cause = message ? ` (Cloudinary ${code || `HTTP ${status}`}: ${message})` : ` (Cloudinary HTTP ${status})`;

  const quotaExhausted = (quota && Number(quota.remaining) <= 0)
    || /limit exceeded|quota|credit|billing|limit reached/i.test(message);
  if (quotaExhausted) {
    return new ServiceUnavailableException(
      `The Cloudinary Image Generation credits for cloud "${cloudName}" are used up`
      + `${quota ? ` (${quota.remaining} of ${quota.limit} remaining)` : ''}. `
      + `Check the plan for that product environment in the Cloudinary console.${cause}`,
    );
  }
  if (status === 429 || category === 'rate_limit_error') {
    return new ServiceUnavailableException(`Cloudinary image generation is rate limited right now. Please try again in a moment.${cause}`);
  }
  if (status === 401) {
    return new ServiceUnavailableException(`Cloudinary rejected the API credentials for cloud "${cloudName}".${cause}`);
  }
  if (/add-?on.*not|not.*(enabled|registered|subscribed|activated)|entitle/i.test(message)) {
    return new ServiceUnavailableException(`${ADDON_NOT_ENABLED} Cloud: "${cloudName}".${cause}`);
  }
  if (status === 400 && /prompt|content|policy|moderation|safety/i.test(message)) {
    return new BadRequestException(`That prompt was rejected by Cloudinary image generation. Please rephrase it.${cause}`);
  }
  return new ServiceUnavailableException(`Cloudinary image generation failed.${cause}`);
}

/** Downloads generated bytes so they can go through the normal media pipeline. Restricted to
 *  Cloudinary hosts — this never fetches an arbitrary URL. */
export async function fetchGeneratedImage(url: string): Promise<Buffer> {
  if (!isCloudinaryUrl(url)) throw new ServiceUnavailableException('Cloudinary returned an unexpected image location.');
  const res = await fetch(url);
  if (!res.ok) throw new ServiceUnavailableException('The generated image could not be retrieved from Cloudinary.');
  return Buffer.from(await res.arrayBuffer());
}
